name: Retag images on-demand

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source image'
        required: true
      tag:
        description: 'Source tag'
        required: true
        default: 'latest'
      name:
        description: 'New image name'
        required: true
      architectures:
        description: 'Architectures to build for. Space separated list.'
        required: true
        default: 'linux/amd64 linux/arm64'


jobs:

  retag:
      name: Retag image
      runs-on: ubuntu-latest

      steps:
        - name: Docker login
          uses: docker/login-action@v3
          with:
            registry: "mine.jfrog.cyberjake.xyz"
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Retag image
          run: |
            echo "Retagging ${{ github.event.inputs.source }}:${{ github.event.inputs.tag }} to mine.jfrog.cyberjake.xyz/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}"
            image=${{ github.event.inputs.source }}:${{ github.event.inputs.tag }}
            new_image=mine.jfrog.cyberjake.xyz/${{ github.event.inputs.name }}:${{ github.event.inputs.tag }}
            for platform in ${{ github.event.inputs.architectures }}; do
              docker pull $image --platform $platform
              docker tag $image $new_image
              docker push $new_image
            done
            

