name: Retag images


on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      built_matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:  
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Matrix
        id: set-matrix
        run: python3 build-matrix.py
          

  retag:
      name: Retag images
      runs-on: ubuntu-latest
      needs: matrix
      strategy:
        matrix:
          ${{ insert }}: ${{ fromJson(needs.matrix.outputs.built_matrix) }}

      steps:
        - name: Docker login
          uses: docker/login-action@v3
          with:
            registry: "mine.jfrog.cyberjake.xyz"
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Retag image
          run: |
            echo "Retagging $image"
            image=${{ matrix.source }}:${{ matrix.tag }}
            new_image=mine.jfrog${{ matrix.name }}:${{ matrix.tag }}
            for platform in ${{ matrix.architectures }}; do
              docker pull $image --platform $platform
              docker tag $image $new_image
              docker push $new_image
            done
            

